using PainelGerencial.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PainelGerencial.Repository
{
    public interface INovosNegociosRepository
    {
        public IEnumerable<dynamic> Marcas();
        public IEnumerable<dynamic> UsuariosDepartamentoLista();
        public IEnumerable<dynamic> UsuariosDepartamentoRelatorio();
        public IEnumerable<dynamic> PlanoAcaoRelatorio(int marca, string responsavel, DateTime data_reuniao, int efetividade);
        public IEnumerable<dynamic> PlanoAcaoRelatorioMes(int? mes);
        public IEnumerable<dynamic> PlanoAcaoRotinaAviso();
        public IEnumerable<dynamic> PlanoAcaoItemRotinaAviso();
        public IEnumerable<dynamic> DadosPlanoAcao(long id);
        public IEnumerable<dynamic> DadosPlanoAcaoItens(long id);
        public IEnumerable<dynamic> MarcaNome(int id);
        public IEnumerable<PlanoAcaoItem_Model> PlanosAcaoItens(long planoAcaoCodigo);
        public IEnumerable<dynamic> itens_pai(long? item_pai_id);
        public IEnumerable<dynamic> itens_filhos(long? item_pai_id);
        public string codigo_item(List<PlanoAcaoItem_Model> codigos_plano_acao_item, long? plano_acao_codigo, int plano_acao_item_codigo);
        public IEnumerable<dynamic> Filhos(int idPai);
        public IEnumerable<dynamic> PlanoAcaoItensObservacaoRelatorioAprovar();
        public IEnumerable<dynamic> PlanoAcaoDatas();
        public IEnumerable<dynamic> AgendaRelatorioCalendario();
        public IEnumerable<dynamic> AvaliacaoAgenda(int agenda);
        public string validacao_setores_agenda(int setor, long intervalo_dias_reuniao);
        public IEnumerable<dynamic> AgendaInvites(DateTime? inicio, DateTime? fim);
        public List<dynamic> PlanoAcaoQtdeUsuarioEfetividade(string usuario);
        public IEnumerable<dynamic> QtdeObservacoes(long? plano_acao_item_id);
        public IEnumerable<dynamic> RetornoPlanoAcaoItens(string? usuario);
        public IEnumerable<dynamic> AgendaRelatorio(DateTime? dataAgenda, string? responsavel);
        public long AgendaStatusSetor(long agenda, int setor, string comentario, long usuario, string usuario_email, string usuario_nome, string arquivo);
        public IEnumerable<dynamic> ObservacoesItens(long plano_acao_item);
        public IEnumerable<dynamic> plano_acao_inserir(PlanoAcao_Model planoAcao);
        public int plano_acao_editar(PlanoAcao_Model planoAcao);
        public IEnumerable<dynamic> usuario_Id(string email);
        public IEnumerable<dynamic> UsuarioPorId(string responsavel);
        public IEnumerable<dynamic> VoltaStatusEmAndamento(long? plano_acao_item_pai);
        public IEnumerable<dynamic> InserirPlanoAcaoItem(PlanoAcaoItem_Model planoAcaoItem);
        public int AlteraPlanoAcaoItem(PlanoAcaoItem_Model planoAcaoItem);
        public IEnumerable<dynamic> PlanoAcaoPai(long id);
        public IEnumerable<dynamic> dados_item_filho(long? id);
        public IEnumerable<dynamic> PlanoAcaoItensGravar(PlanoAcaoItem_Model planoAcaoItem);
        public IEnumerable<dynamic> plano_acao_item_progresso(long id);
        public IEnumerable<dynamic> FornecedorNome(int id);
        public IEnumerable<PlanoAcaoItem_Model> DadosItensFilhos(long plano_acao_item_id);
        public IEnumerable<dynamic> PlanoAcaoItensObservacao(int item);
        public IEnumerable<dynamic> SolicitacaoNaoAprovada(long plano_acao_item);
        public int PlanoAcaoItensObservacaoAtualizar(PlanoAcaoItemObservacao observacao);
        public int PlanoAcaoItensObservacaoGravar(PlanoAcaoItemObservacao observacao);
        public IEnumerable<dynamic> dados_plano_acao(long planoAcaoId);
        public IEnumerable<PlanoAcaoItem_Model> codigos_plano_acao_item(long planoAcaoId);
        public IEnumerable<PlanoAcaoItem_Model> dados_plano_acao_item(long planoAcaoId);
        public IEnumerable<PlanoAcaoItem_Model> PlanoAcaoItemPorId(long idPlanoAcaoItem);
        public IEnumerable<PlanoAcaoItem_Model> PlanoAcaoItemPorPlanoAcao(long idPlanoAcao);
        public IEnumerable<dynamic> data_prazo_em_aprovacao(long idObservacao);
        public int ExcluiPlanoAcaoItemObservacao(long idObservacao);
        public IEnumerable<PlanoAcaoItem_Model> CodigosPlanoAcaoItem(long idPlanoAcaoItem);
        public int ExcluirPlanoAcaoItemResponsavel(int idItem);
        public int ExcluirPlanoAcaoItem(long idItem);
        public int ExcluirItensPorPlanoAcao(long idPlano);
        public int ExcluirPlanoAcao(long idPlano);
        public IEnumerable<PlanoAcaoItemObservacao> dados_observacao(long idObs);
        public int AprovarPlanoAcaoItemObservacao(int aprovado, long usuario, string usuario_nome, string usuario_email, long idItem, DateTime data_prazo);
        public int ConcluiPlanoAcaoItem(long idItem, int efetividade);
        public IEnumerable<dynamic> EmailRelatorio();
        public IEnumerable<dynamic> AgendaDatas();
        public IEnumerable<dynamic> InsereAgenda(Agenda_Model agenda);
        public int AlteraAgenda(Agenda_Model agenda);
        public IEnumerable<dynamic> AgendaPorId(long id);
        public int ExcluirAgendaInteracoes(long id);
        public int ExcluirAgenda(long id);
        public IEnumerable<dynamic> avaliacao_existente(long agenda, int setor);
        public IEnumerable<dynamic> InsereAgendaAvaliacao(Agenda_Avaliacao_Model agendaAvaliacao);
        public int AlteraAgendaAvaliacao(Agenda_Avaliacao_Model agendaAvaliacao);
        public IEnumerable<dynamic> AgendaAvaliacoes();
        public IEnumerable<dynamic> AgendaAvaliacao(long id);
        public IEnumerable<dynamic> AgendaRotinaAviso();
        public IEnumerable<dynamic> AgendaInteracoes(long id);
        public IEnumerable<dynamic> AgendaInteracoesPorId(long id);
        public int AtualizaNomeArquivo(long id, string arquivo);
        public IEnumerable<dynamic> Fornecedores();
        public IEnumerable<dynamic> EmailDados(long id);
        public int EmailDeletar(long id);
        public int UsuariosDepartamentoDeletar(long id);
        public bool VerificaUsuarioExistente(string email);
        public long UsuariosDepartamentoInserir(Usuarios_Model usuario);
        public int UsuariosDepartamentoAtualizar(Usuarios_Model usuario);
        public IEnumerable<dynamic> setor_nome(int setor);
        public long EmailsInserir(Emails_Model email);
        public int EmailsAtualizar(Emails_Model email);
        public IEnumerable<dynamic> arquivos_padroes();
        public int ArquivosPadroesInserir(Arquivos_Padroes_Model arquivo);
        public int ArquivosPadroesAtualizar(Arquivos_Padroes_Model arquivo);
        public Arquivos_Padroes_Model ArquivosPadroesPorId(int id);
        public int ArquivosPadroesDeletar(int id);
        public IEnumerable<dynamic> dashboard_atrasados();
        public IEnumerable<dynamic> QtdEmAndamento(string email);
        public IEnumerable<dynamic> QtdConcluido(string email);
        public IEnumerable<dynamic> QtdAtrasados(string email);
        public IEnumerable<dynamic> QtdPlanoAcaoItem();
        public IEnumerable<dynamic> QtdPlanoAcaoItemEmAndamento();
        public IEnumerable<dynamic> QtdPlanoAcaoItemEmAtraso();
        public IEnumerable<dynamic> QtdPlanoAcaoItemConcluidosNoPrazo();
        public IEnumerable<dynamic> QtdPlanoAcaoItemConcluidosComAtraso();
        public IEnumerable<dynamic> QtdPlanoAcaoItemAguardandoData();
        public IEnumerable<dynamic> PlanoAcaoItem();
        public int? ResponsavelId(string email, string nome, int? ticked);
        public int ResponsavelInserir(string email, string nome, int? ticked);
        public int PlanoAcaoItemResponsavelInserir(int idPlanoAcaoItem, int idResponsavel);
        public IEnumerable<Responsavel_Model> PlanoAcaoItensResponsavel(int idPlanoAcaoItem);
    }
}